# Generated by Django 4.1.1 on 2022-09-22 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('player_nation', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('sleeping_only', models.BooleanField(default=False)),
                ('group_tent', models.BooleanField(default=False)),
                ('colour', models.CharField(max_length=64, null=True)),
                ('occupants', models.IntegerField()),
                ('pd_supplied', models.BooleanField(default=False)),
                ('electric_req', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('tent_on_field', models.CharField(choices=[('IC', 'IC Essential'), ('X', 'Normal'), ('OC', 'OOC Okay')], max_length=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('img', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TentAtEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tents.event')),
                ('tent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tents.tent')),
            ],
        ),
        migrations.CreateModel(
            name='FieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tents.nation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tentatevent',
            constraint=models.UniqueConstraint(fields=('tent', 'event'), name='tent_at_event_only_once'),
        ),
    ]
