# Generated by Django 4.1.1 on 2022-09-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tent", name="notes", field=models.TextField(null=True),
        ),
    ]
