# Generated by Django 4.1.1 on 2022-09-23 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tents", "0003_alter_tent_colour_alter_tent_name_alter_tent_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tent",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tents.fieldgroup",
            ),
        ),
    ]
